In [93]:
import petpy
import pandas as pd

In [3]:
pf = petpy.Petfinder(
    key='Ww9PL1UlVo7Wdj0DeGkkRo6PXKCXdsStCMKQ2Jc9CYvX5OTNPX', 
    secret='7RNX05UlYJdUIbhy90BfgGwG0ZuwWkQTMNeIYAGk'
    )

In [8]:
dogs = pf.animals(pages=100, results_per_page=100, return_df=True)
dogs

,id,organization_id,url,type,species,age,gender,size,coat,tags,...,contact.address.address1,contact.address.address2,contact.address.city,contact.address.state,contact.address.postcode,contact.address.country,animal_id,animal_type,organization_id,primary_photo_cropped
0,54578583,SC300,https://www.petfinder.com/dog/rosie-54578583/s...,Dog,Dog,Adult,Female,Medium,Short,"[Friendly, Affectionate, Gentle, Playful, Athl...",...,1140 South Guignard Drive,None,Sumter,SC,29150,US,54578583,dog,sc300,NaN
1,54578579,GA181,https://www.petfinder.com/dog/hero-1164-545785...,Dog,Dog,Adult,Male,Large,None,[],...,4900 Milgen Rd.,None,Columbus,GA,31908,US,54578579,dog,ga181,NaN
2,54578578,GA181,https://www.petfinder.com/dog/jake-0497-545785...,Dog,Dog,Young,Male,Medium,None,[],...,4900 Milgen Rd.,None,Columbus,GA,31908,US,54578578,dog,ga181,NaN
3,54578576,IN27,https://www.petfinder.com/dog/mandy-54578576/i...,Dog,Dog,Young,Female,Medium,None,[Friendly],...,3355 Bertholet Blvd,None,Valparaiso,IN,46385,US,54578576,dog,in27,NaN
4,54578577,VA253,https://www.petfinder.com/cat/tanner-54578577/...,Cat,Cat,Senior,Male,Large,None,[Bonded],...,415 CAMPBELL AVE SW,None,Roanoke,VA,24016,US,54578577,cat,va253,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,54560372,GA603,https://www.petfinder.com/cat/milo-54560372/ga...,Cat,Cat,Young,Male,Medium,None,[],...,1111 Exum Street,PO BOX 1044,Nashville,GA,31639,US,54560372,cat,ga603,NaN
9996,54560368,GA603,https://www.petfinder.com/cat/sparkita-5456036...,Cat,Cat,Young,Female,Medium,None,[],...,1111 Exum Street,PO BOX 1044,Nashville,GA,31639,US,54560368,cat,ga603,NaN
9997,54560373,GA603,https://www.petfinder.com/cat/diza-54560373/ga...,Cat,Cat,Young,Female,Medium,None,[],...,1111 Exum Street,PO BOX 1044,Nashville,GA,31639,US,54560373,cat,ga603,NaN
9998,54560363,GA603,https://www.petfinder.com/cat/toland-54560363/...,Cat,Cat,Young,Male,Medium,None,[],...,1111 Exum Street,PO BOX 1044,Nashville,GA,31639,US,54560363,cat,ga603,NaN
9999,54560364,GA603,https://www.petfinder.com/cat/demi-54560364/ga...,Cat,Cat,Young,Female,Medium,None,[],...,1111 Exum Street,PO BOX 1044,Nashville,GA,31639,US,54560364,cat,ga603,NaN

In [6]:
dogs.columns

Index(['id', 'organization_id', 'url', 'type', 'species', 'age', 'gender',
       'size', 'coat', 'tags', 'name', 'description', 'organization_animal_id',
       'photos', 'videos', 'status', 'status_changed_at', 'published_at',
       'distance', 'breeds.primary', 'breeds.secondary', 'breeds.mixed',
       'breeds.unknown', 'colors.primary', 'colors.secondary',
       'colors.tertiary', 'attributes.spayed_neutered',
       'attributes.house_trained', 'attributes.declawed',
       'attributes.special_needs', 'attributes.shots_current',
       'environment.children', 'environment.dogs', 'environment.cats',
       'primary_photo_cropped.small', 'primary_photo_cropped.medium',
       'primary_photo_cropped.large', 'primary_photo_cropped.full',
       'contact.email', 'contact.phone', 'contact.address.address1',
       'contact.address.address2', 'contact.address.city',
       'contact.address.state', 'contact.address.postcode',
       'contact.address.country', 'animal_id', 'animal_type',
       'organization_id', 'primary_photo_cropped'],
      dtype='object')

In [10]:
dogs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            10000 non-null  int64
 1   organization_id               10000 non-null  object
 2   url                           10000 non-null  object
 3   type                          10000 non-null  object
 4   species                       10000 non-null  object
 5   age                           10000 non-null  object
 6   gender                        10000 non-null  object
 7   size                          10000 non-null  object
 8   coat                          2169 non-null   object
 9   tags                          10000 non-null  object
 10  name                          10000 non-null  object
 11  description                   6263 non-null   object
 12  organization_animal_id        7785 non-null   object
 13  photos                        10000 non-null  object
 14  videos                        10000 non-null  object
 15  status                        10000 non-null  object
 16  status_changed_at             10000 non-null  object
 17  published_at                  10000 non-null  object
 18  distance                      0 non-null      object
 19  breeds.primary                10000 non-null  object
 20  breeds.secondary              2996 non-null   object
 21  breeds.mixed                  10000 non-null  bool
 22  breeds.unknown                10000 non-null  bool
 23  colors.primary                4978 non-null   object
 24  colors.secondary              2184 non-null   object
 25  colors.tertiary               144 non-null    object
 26  attributes.spayed_neutered    10000 non-null  bool
 27  attributes.house_trained      10000 non-null  bool
 28  attributes.declawed           3781 non-null   object
 29  attributes.special_needs      10000 non-null  bool
 30  attributes.shots_current      10000 non-null  bool
 31  environment.children          2219 non-null   object
 32  environment.dogs              2443 non-null   object
 33  environment.cats              2067 non-null   object
 34  primary_photo_cropped.small   8665 non-null   object
 35  primary_photo_cropped.medium  8665 non-null   object
 36  primary_photo_cropped.large   8665 non-null   object
 37  primary_photo_cropped.full    8665 non-null   object
 38  contact.email                 9347 non-null   object
 39  contact.phone                 8334 non-null   object
 40  contact.address.address1      6997 non-null   object
 41  contact.address.address2      650 non-null    object
 42  contact.address.city          10000 non-null  object
 43  contact.address.state         10000 non-null  object
 44  contact.address.postcode      10000 non-null  object
 45  contact.address.country       10000 non-null  object
 46  animal_id                     10000 non-null  object
 47  animal_type                   10000 non-null  object
 48  organization_id               10000 non-null  object
 49  primary_photo_cropped         0 non-null      float64
dtypes: bool(6), float64(1), int64(1), object(42)
memory usage: 3.4+ MB

In [15]:
dogs['breeds.primary'].value_counts()[dogs['breeds.primary'].value_counts() > 50]

Domestic Short Hair                    2793
Pit Bull Terrier                        788
Mixed Breed                             759
Labrador Retriever                      628
Shepherd                                315
Domestic Medium Hair                    307
German Shepherd Dog                     301
Terrier                                 286
Chihuahua                               284
Domestic Long Hair                      213
Hound                                   163
Australian Cattle Dog / Blue Heeler     142
Boxer                                   137
Tabby                                   119
Beagle                                  116
American Staffordshire Terrier          113
Siberian Husky                          108
Husky                                   107
Australian Shepherd                      88
American Bulldog                         86
Border Collie                            85
Great Pyrenees                           72
Siamese                                  72
Retriever                                63
Dachshund                                54
Name: breeds.primary, dtype: int64

In [23]:
dogs['environment.children'].dropna().value_counts(normalize=True)

True     0.915728
False    0.084272
Name: environment.children, dtype: float64

In [ ]:
# https://github.com/aschleg/petpy/blob/master/petpy/api.py